-- Revisado por    :  
-- Funcionalidad   :  Listado de Pedidos - Delivery
-- Utilizado por   :  MEDISANNA
--
-- Entrada         : 
--                     
--		               
--		               
--
-- Salida          :  Listado de Pedidos - Delivery
--
-- Nro        Fecha          Autor        	Descripcion
-- ====================================================================================
-- 1          18/02/2025     WVILCA	 		Listado
---------------------------------------------------------------------------------------
	ALTER PROCEDURE SPRMDS_LIST_HISTORIA_CLINICA_MAD_DELIVERY_FILTRO
	@INICIO 					INT 			= 0,
	@PAGINA			 			INT 			= 10,
	@ORDENAR					CHAR(200)		= NULL
	AS
		BEGIN
			SET NOCOUNT ON
			--DECLARACION DE VARIABLES
			DECLARE @VCADENASQL			NVARCHAR(MAX)	= ''
			DECLARE @vFILAS 			NVARCHAR(MAX) 	= ''
			DECLARE @vPARAMETROS 		NVARCHAR(MAX) 	= ''
			DECLARE @vORDENAR 			VARCHAR(MAX) 	= ''
			DECLARE @vFILTRO 		VARCHAR(MAX) 	= ''
 			DECLARE @vPAGINACION 		VARCHAR(MAX) 	= ''
			DECLARE @vTOTAL 			INT 			= 0
			DECLARE @VCADSQL			NVARCHAR(MAX)	= ''
			--NUMERO DE FILAS DEVUELTAS SEGUN LA CONSULTA REALIZADA
			SET @vFILAS = '
						SELECT  @vTOTAL = COUNT(PED.CPED_ID) 
						FROM TBLMDS_PEDIDO_MEDICINA PED
						WHERE 1 = 1			
						'
			--VALOR DE SALIDA
			SET @vPARAMETROS = '
							@vTOTAL INT OUT
						'
			--CAMPOS A MOSTRAR EN LA CONSULTA
			SET @VCADENASQL = '
			SELECT 
					CASE WHEN PED.FPED_SEGUI_PED = 1 THEN ''SI'' ELSE ''NO'' END AS SEGUI_PEDI,
					PED.NPED_ESTADO,
					PED.SPED_FLAG_TP,
					PED.SPED_CANC_PED,
					PED.CPED_ID,
					CASE WHEN PED.FPED_FLG_VALIDADO = 1 THEN ''SI'' ELSE ''NO'' END AS FLG_VALIDADO,
					CASE WHEN PED.NPED_CONDICION_PEDIDO IS NULL THEN '''' 
						 WHEN PED.NPED_CONDICION_PEDIDO = 0 THEN ''AUDITADO'' 
						 WHEN PED.NPED_CONDICION_PEDIDO = 1 THEN ''OBSERVADO''
						 WHEN PED.NPED_CONDICION_PEDIDO = 2 THEN ''CON STOCK'' END AS CONDICION_PED,
					PED.SPED_FLG_PROG,
					PED.CPED_CODIGO_HISTORIACLINICA AS COD_ATE,
					CASE 
						WHEN H.NHIS_CONTADOR_PERIODO = 1 THEN ''CRTL'' 
					ELSE
						CASE 
							WHEN H.SHIS_COD_TIPO_SEG_CRONICO = ''1'' THEN ''SEG*'' ELSE ''SEG'' END END PERFIL_ATE,
					CASE 
						WHEN PED.CPED_CODIGO_HISTORIACLINICA = 999999 
							THEN SN.SSER_NOMBRE 
					ELSE SN.SSER_NOMBRE END AS CLASIF, 
					PED.DPED_FECLLA_PED,
					PED.DPED_HORLLA_PED,
					PED.DPED_FEC_PED,
					PED.SPED_NOM_CAMFAR,
					PMO.SPMO_DESCRIPCION AS PROVEEDOR_MOT,
					OE.SOLV_DESCRIPCION AS DESCRIPCION_OLVAE,
					PER.SPER_NOMBRES + '' '' + PER.SPER_APELLIDO_PATERNO + '' '' + PER.SPER_APELLIDO_MATERNO AS NOM_DOC,
					PED.SPED_USULLA_PED,
					CONVERT(VARCHAR,PED.DPED_FEC_PED,23) AS FECHA,
					CONVERT(VARCHAR,PED. DPED_HORASGMED_PED,108) AS HORA,
					CASE 
						WHEN SN.SSER_NOMBRE = ''MEDICINA COMPLEJA'' OR 
						SN.SSER_NOMBRE = ''DELIVERY PACIFICO'' THEN ''BLANCO''
					ELSE
						''ROJO'' END AS OBTENER_COLOR,
					CASE 
						WHEN PED.CPED_CODIGO_HISTORIACLINICA = 999999 THEN
							CASE 
								WHEN PED.NPED_CLASIFICACION_PED IS NULL THEN 0
							ELSE PED.NPED_CLASIFICACION_PED END 
						ELSE SN1.CSER_ID END COD_CLASIF
				FROM TBLMDS_PEDIDO_MEDICINA PED 
				LEFT JOIN TBLMDS_SERVICIO_NEGOCIO SN ON PED.NPED_CLASIFICACION_PED = SN.CSER_ID 
			    LEFT JOIN TBLMDS_MOTORIZADO MO ON PED.SPED_CODIGO_MOTORIZADO = MO.CMOT_PK_POSTGRES_COD_MOT 
			    LEFT JOIN TBLMDS_PROVEEDOR_MOTORIZADO PMO ON PMO.CPMO_PK_POSTGRES_PROVEEDOR_MOTORIZADO = MO.CMOT_PK_POSTGRES_COD_PROV_MOTORIZADO  
			    LEFT JOIN TBLMDS_UBIGEO U ON  U.CUBI_ID = PED.CPED_CODIGO_UBIGEO
				LEFT JOIN TBLMDS_FARMACIA F ON F.SFAR_PK_POSTGRES_COD_FAR = PED.SPED_COD_CAMFAR
				LEFT JOIN TBLMDS_HISTORIA_CLINICA H ON PED.CPED_CODIGO_HISTORIACLINICA = H.CHIS_ID
				LEFT JOIN TBLMDS_MEDICO M ON M.CMED_ID = H.CMED_ID
				LEFT JOIN TBLMDS_PERSONA PER ON PER.CPER_ID = M.CPER_ID
				LEFT JOIN TBLMDS_SERVICIO_NEGOCIO SN1 ON H.CSER_ID = SN.CSER_ID
				LEFT JOIN TBLMDS_OLVA_ESTADOS OE ON PED.SPED_ULT_COD_OLVA = OE.SOLV_PK_POSTGRES_CODIGO
				WHERE 1=1'
				--MOSTRAR PEDIDOS SOLO DEL DIA DE HOY
				SET @vFILTRO += ' AND PED.DPED_FEC_PED  = ''' + GETDATE() + ''' ' + CHAR(13)
				
	--ORDENAR SEGUN EL CAMPO INGRESADO
	IF (ISNULL(@ORDENAR,'') <> '')
		SET @vORDENAR+=' ORDER BY '+ @ORDENAR
	--INICIO DE LA PAGINACION
	IF(@PAGINA > 0)
	BEGIN
  		SET @vPAGINACION = ' 
								OFFSET ' + (CAST(@INICIO AS varchar(10))) + ' ROWS
  								FETCH NEXT ' + (CAST(@PAGINA AS varchar(10))) + ' ROWS ONLY
							'
 	END
	--VERIFICAMOS CUANTAS FILAS DEVUELVE LA CONSULTA
	SET @vFILAS += @vFILTRO
	--EJECUTAMOS LA CONSULTA DINAMICA
	EXECUTE sp_executesql 
	@VFILAS,
	@vPARAMETROS,
	@vTOTAL = @vTOTAL OUT
	--VERIFICAMOS EL NUMERO DE FILAS
	SELECT @vTOTAL AS 'TOTAL'
	--CONCATENAMOS TODAS LAS VARIABLES
	IF(@vFILTRO <> '') 		SET @VCADENASQL += @vFILTRO
	IF(@vORDENAR <> '') 	SET @VCADENASQL += @vORDENAR
	IF(@vPAGINACION <> '') 	SET @VCADENASQL += @vPAGINACION
	--MOSTRAMOS POR PANTALLA LA CONSULTA
	PRINT @vTOTAL
	PRINT @VCADENASQL
	--EJECUTAMOS EL SP
	EXEC SP_EXECUTESQL @VCADENASQL
END
